### ISSUE TITLE
[Reflection] 1주차 김지욱 

### ISSUE THREAD

**Issue by Jiwook00** [codestates/Biba-Server#31]
## 10.07 화
 대망의 4주 프로젝트가 시작되었다!
### 오늘 한 일
- 프로젝트 선정
- 팀명과 역할 정하기
- [프로젝트 기획 및 범위 설정](https://github.com/codestates/Biba-Client/wiki/Requirements)

---
## 10.08 수
백엔드 에서 새롭게 배우게 될 메인 스택으로 타입스크립트와 몽고DB 채택 되었다. 
구체적인 SR 계획은 주말동안 새로운 스택을 공부하고 정하기로 했다.
### Todo
- [ ] MongoDB 설치하기

---
## 10.09 목
이전 프로젝트에서도 백엔드를 했기 때문에 조금 수월하지 않을까 생각했는데 
타입스크립트와 몽고디비를 만나고 그런 생각이 싹 사라졌다.:sweat_smile:
### Todo
- [x] Compase 설치해서 사용
- [x] express + mongoose 사용해서 post 로 데이터 넣어보기
- [x] MVC 패턴으로 적용

---
## 10.10 금 
어제까지 작성한 파일들을 타입스크립트로 리팩토링을 시도해 봤지만 생각보다 쉽지 않았다.
타입스크립트 그 차제로는 괜찮은 거 같은데 이것저것에 적용하려고 하니까 머리가 아프다:fearful:

---
## 10.11 토
아마도 마주막 주말이 되지 않을까
아직 있는 여유를 조금 느끼면서 보냈다.
### Todo
- [x] 타입스크립트 기본 공식문서 부분 따라하기

---
## 10.12 일
주말동안 타입스크립트와 몽고DB 이것저것 손을 대보기는 했는데 잘 모르겠다.
계획했던 결과가 나오지 않아서 아쉽다.
### Todo
- [ ] MogoDB(mongoose) + express + typescript 로 뭐든 DB에 넣어보기

### Todo

---
## 10.13 화
SR이 거의 끝났다. 주말이 포함되어 있어서 그런가 생각보다 오래 걸린 느낌이었지만 
지난번 보다 완성도가 훨씬 좋게 나온거 같다.
윤연님의 [와이어 프레임](https://lucid.app/lucidchart/39e64332-6146-437e-aa20-a683e6e41bec/view?page=0_0#?folder_id=home&browser=icon)을 보고 정말 감탄을 했다.. :thumbsup:
모하지 팀에서 만들었던건 와이어 프레임이 아니었구나 

### Todo
- [x] 서버 플로우 차트 마무리하기
- [x] MVC 패턴으로 백엔드 기본 구조 짜기
  - [타입스크립트로 적용하는 부분에서 예상치 못한 오류가 생겼다](https://velog.io/@beton/TIL-20.10.14-export-default-import)

---
## 1주차 회고 5F

**Fact(사실)**
- 4주 프로젝트에서 백엔드를 담당하게 되었다.
- 기본 스택으로 타입스크립트와 몽고DB를 선택하고 학습했다.
- 하지만 시간안에 할수 있을거라는 확신이 없어서 몽고 DB대신 익숙한 시퀄라이즈를 사용하기로 했다.

**Feeling(느낌)**
- 타입스크립트를 사용하면 이점이 많다고 하지만 아직까진 불편함이 더 큰거 같다.
- 타입스크립트 + 몽고DB, 새롭게 배우는 두 가지를 한번에 적용하려고 하니까 너무 막막했다.
- 시퀄라이즈 역시 타입스크립트로 생각하려고 하니까 하나도 익숙하지 않았다.

**Finding(교훈)**
- 무언가 새롭게 학습하기 전에 큰그림을 그려보면 좋을 거 같다.
    - 내가 이걸 배우는데 얼마나 시간이 걸릴지
    - 그렇게 해서 알게 되었을 때 다음 단계는?
    - 이걸 어떻게 활용할 수 있을지, 추가적으로 학습해야 할 게 있을지

**Future action(행동)**
- 익숙하지 않고 어려운 문제에서는 한번에 다 해결하려고 하지말고 단계별로 하나씩 진행하면 좋을 거 같다.
