### ISSUE TITLE
[Reflection] 2주차 김지욱

### ISSUE THREAD

**Issue by Jiwook00** [codestates/Biba-Server#32]
## 10.14 수
몽고DB를 하지않게 되었지만 타입스크립트로 리팩토링을 해야 한다는 점에서는 시퀄라이즈 역시나 쉽지만은 않아보인다. 그래도 몽고DB 보다는 괜찮은 레퍼런스들이 많고, 한 번 해봤던 거라서 초반 세팅만 잘 잡아두면 조금은 수월하지 않을까
### Todo
- [x] eslint와 prettier 설정 완료하기
- [x] 모델 구성해서 DB에 연결하기

---
### Todo
- [x] 어제 작업 머지하고 재현님과 작업내용 동기화 시키기
- [ ] 테이블 관계도 구성 완료하기
- [ ] 리스트 API 만들기
- [x] 위키에 DB 스키마 올리기

---

### Todo
- [x] 테이블 관계도 구성 완료하기
- [ ] 맥주 리스트 전체 보여주기
- [x] 맥주 상세 보기 페이지

---
### Todo
- [ ]
